### ISSUE TITLE
Multi-line array recurses infinitely

### ISSUE THREAD

**Issue by JakeWharton** [akuleshov7/ktoml#126]
Using 0.2.11:
```kotlin
@Serializable
data class Config(
  val items: List<String>,
)
```
```toml
items = [
  "hey",
  "hi",
]
```
```kotlin
Toml.decodeFromString(Config.serializer(), toml.readText())
```
```
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.lang.String.startsWith(String.java:2297)
	at kotlin.text.StringsKt__StringsJVMKt.startsWith(StringsJVM.kt:418)
	at kotlin.text.StringsKt__StringsJVMKt.startsWith$default(StringsJVM.kt:416)
	at com.akuleshov7.ktoml.parsers.StringUtilsKt.trimSymbols(StringUtils.kt:151)
	at com.akuleshov7.ktoml.parsers.StringUtilsKt.trimBrackets(StringUtils.kt:83)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parseArray(TomlValue.kt:247)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:237)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
	at com.akuleshov7.ktoml.tree.TomlArray$Companion.parse(TomlValue.kt:239)
```
Works fine when I change it to
```toml
items = ["hey", "hi"]
```

**Comment by akuleshov7** [comment]
Yeah 😢 Multiline arrays are not yet supported as well as multiline strings: https://github.com/akuleshov7/ktoml/issues/46
But I actually thought we will have a proper warning on this, I suppose we should fix that after the end of the war.

**Comment by JakeWharton** [comment]
Ah, I did see that issue but didn't realize it affected arrays as well.

But worry about yourself first. Stay safe. Slava Ukraini!
