### ISSUE TITLE
TomlTable.write() throws NoSuchElementException if children is empty

### ISSUE THREAD

**Issue by thomasgalvin** [akuleshov7/ktoml#226]
```kotlin
@Test
    fun emptyArrayInTableTest(){
        @Serializable
        data class EmbeddedData(val data: String = "embedded data")

        @Serializable
        data class EmptyListData(val content: List<EmbeddedData> = listOf() )
        
        assertEncodedEquals(
            value = EmptyListData(),
            expectedToml = ""
        )
    }
```

Throws:

```
List is empty.
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at com.akuleshov7.ktoml.tree.nodes.TomlTable.write(TomlTable.kt:83)
```

**Comment by akuleshov7** [comment]
Will be in the nearest minor release
